import React from "react";

function Verticals() {
  return (
    <section className="section">
      <div className="bg-sky-100 text-center py-8 mt-8">
        <h1 className="text-2xl font-extrabold text-slate-700 mb-4">Category Verticals</h1>
        <div className="flex flex-wrap justify-center gap-4 cursor-pointer">
          <button className="bg-white font-medium text-slate-500 rounded-md w-64 h-14">🧠 AI</button>
          <button className="bg-white font-medium text-slate-500 rounded-md w-64 h-14">⚙️ No Code</button>
          <button className="bg-white font-medium text-slate-500 rounded-md w-64 h-14">💻 Developer Tools</button>
          <button className="bg-white font-medium text-slate-500 rounded-md w-64 h-14">👨‍🎨Design Tools</button>
          <button className="bg-white font-medium text-slate-500 rounded-md w-64 h-14">💻 API</button>
        </div>
        <div className="mt-8">
          <h5 className="text-2xl font-extrabold text-slate-700 mb-4">Featured products</h5>
          <div className="flex flex-wrap justify-center gap-6 cursor-pointer">
            {[
              { src: "cat-logo-1.png", text: "Create in-app experiences with most straightforward product..." },
              { src: "cat-logo-2.png", text: "Daily AI sports picks generated by artificial intelligence." },
              { src: "cat-logo-3.png", text: "AirDroid Business, an enterprise-grade MDM solution, is designed to..." },
              { src: "cat-logo-4.png", text: "Grow Revenue, Reduce Customer Churn, Retain Customer." },
              { src: "cat-logo-5.png", text: "FineVoice is a versatile AI voice studio, providing personalized..." },
              { src: "cat-logo-6.png", text: "Clear, Fast & Unlimited." },
            ].map((product, idx) => (
              <div className="flex flex-col items-center w-48" key={idx}>
                <img src={product.src} className="w-[48px] h-[48px] cursor-pointer rounded-sm" alt="logo" />
                <p className="mt-2 text-sm font-normal text-slate-600 w-40 text-center">{product.text}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}

export default Verticals;
